sudo: false

language: python

os:
  - linux

python:
  - 3.5

env:
  global:
    - MINICONDA_VERSION="latest"
    - JAVA_HOME="$(dirname $(which java))"


script:
  - echo $JAVA_HOME
  - pytest -V tests/test_workflows.py
  - pytest --cov-report=term --cov=tests tests/test_rules.py

  
branches:
  only:
    - master
    - develop
    - /^feature.*$/
    - /^\d+.\d+.\d+$/
    - /^\d+.\d+.\d+dev\d+$/
    - /^\d+.\d+.\d+alpha\.\d+$/
    - /^\d+.\d+.\d+alpha\.\d+dev\d+$/
    - /^\d+.\d+.\d+beta\.\d+$/
    - /^\d+.\d+.\d+beta\.\d+dev\d+$/

before_install:
    - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - scripts/travis-setup.sh

after_success:
  coveralls

