dependencies:
  - bamtools
  - bedtools
  - blat
  - bowtie
  - bowtie2
  - bwa
  - cutadapt
  - diamond
  - emboss
  - fastqc
  - gatk
  - htslib
  - jellyfish
  - picard
  - plink2
  - pysam
  - qualimap
  - rsem
  - samtools
  - snpeff
  - sra-tools
  - star
  - trim-galore
  - trimmomatic
  - vcftools
  - vsearch

  # Ucsc binaries
  - ucsc-bedgraphtobigwig
  - ucsc-fetchchromsizes
  - ucsc-genepredtobed
  - ucsc-gtftogenepred
  - ucsc-wigtobigwig

  # Missing 
  # - gem
  # - homer
  # - centipede
  # - danpos
  # - dfilter
  # - tuxedo
  # - ucsc
  # - vcf

    
  # Never via conda
  # - annovar

  # Non-package rules
  # - cloudbiolinux
  # - ercc
  # - multo
  # - rnaseqc
