{% set name = "snakemake-rules" %}
{% set release = "0.2.2" %}
{% set release_short = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ release_short }}
source:
  path: ../../snakemake-rules
build:
  number: 1

requirements:
  build:
    - python >=3.3
    - setuptools
    - snakemake >=3.4.2
    - pytest >=3.0
    - pytest-runner
    - psutil

  run:
    - python >=3.3
    - snakemake
    - pyyaml
    - pytest >=3.0

test:
  requires:
    # docs
    - sphinx >=1.3.1

    # tests
    - coverage
    - pytest >=3.0
    - pytest-cov

    # workflows
    - bwa >=0.7.12
    - samtools >=1.3
    - bcftools >=1.3.1
    - picard >=2.7.1

  imports:
    - snakemake_rules

about:
  home: https://github.com/percyfal/snakemake-rules.git
  license: MIT License
  summary: 'Library of snakemake rules. The rules can be used as-is without installing snakemakelib itself.'
