package:
  name: snakemake-rules
  version: "0.1b.9"
source:
  git_rev: "0.1-beta.9"
  git_url: https://github.com/percyfal/snakemake-rules
requirements:
  build:
    - python ==3.4.3 # As with snakemake
    - setuptools
    - snakemake >=3.4.2

  run:
    - python >=3.3
    - snakemake
    - pyyaml

test:
  requires:
    # docs
    - sphinx >=1.3.1
    - sphinx-bootstrap-theme

    # tests
    - coverage
    - flake8
    - mock
    - pytest
    - pytest-cov ==1.8.1

    # workflow
    - bwa ==0.7.12
    - samtools ==1.3

  imports:
    - snakemake
    
about:
  home: https://github.com/percyfal/snakemake-rules.git
  license: MIT License

  summary: 'Library of snakemake rules. The rules can be used as-is without installing snakemakelib itself.'
  
